version: '3'

services:
  web:
    build: ./web
    depends_on:
      - app-server
    ports:
      - "8080:80"
    restart: always
    volumes_from:
      - app-server
    volumes:
      - ./web/public:/root/public
    networks:
      - local-net

  db:
    container_name: "db"
    build: ./db
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - local-net
    restart: always
    tty: true

  app-server:
    container_name: "app-server"
    build: ./application
    ports:
      - "80:80"
    expose:
      - 80
    links:
      - db
    networks:
      - local-net


networks:
  local-net:
    driver: bridge